vdumchenko/nav-fix
BesedinGeny/mathsite_frontend pull request #1
Opened 2022-09-21 15:20 UTC by Juffin-U

2022-09-21 22:33 UTC, danilkach commented on src/views/HomePage.vue
> +      <div class="testItem" v-for="item in arrOfLinks" :key="item"></div>
Что такое `testBody`, `testBlock` и `testItem`?

2022-09-21 22:34 UTC, danilkach commented on src/views/HomePage.vue
> +      arrOfLinks: ["Главная", "Материалы", "Услуги"],
А это здесь зачем, если такой же массив в NavComponent.vue есть?

2022-09-21 22:34 UTC, danilkach commented on src/views/HomePage.vue
> +  .testBody{
То же самое со стилями

2022-09-21 22:35 UTC, danilkach commented on src/components/NavComponent.vue
> +.linksAndEnter
Ссылки и входить? Непонятное название стиля

2022-09-21 22:36 UTC, danilkach commented on src/components/NavComponent.vue
> +.navDesktop
Мы будем отдельный стиль для nav в мобилке делать?

2022-09-21 22:37 UTC, danilkach commented on src/components/NavComponent.vue
> +      arrOfLinks: ["Главная", "Материалы", "Услуги"],
Naming. И так понятно, что это массив, нет смысла добавлять `arr` или `array` к названию

2022-09-21 22:40 UTC, danilkach commented on src/components/NavComponent.vue
> +      <input type="image" class="Enter" :src="require(`@/assets/Enter.png`)" />
Вход на сайт - это login, никак не Enter

2022-09-21 22:44 UTC, danilkach commented on src/components/NavComponent.vue
> +      <div class="links">
Опять же, naming. Нужно поразмыслить, какие сущности верстаются. Links - это ссылки, например, такие:
`https://natribu.org/`
`http://0.0.0.0:5000/`
`https://yandex.ru/`
В рамках навигационной панели, как я понял из контекста этого компонента, ты делаешь навигационные кнопки, поэтому называть их ссылками некорректно

2022-09-21 22:46 UTC, danilkach commented on src/components/NavComponent.vue
> +          {{ item }}
Не размещай текст в div'ах. Используй ```<p>``` или более уместный здесь ```<span>```

2022-09-21 22:47 UTC, danilkach commented on src/components/NavComponent.vue
> +  <div class="navDesktop">
Почему Desktop?

2022-09-21 22:49 UTC, danilkach commented on src/App.vue
> +<script>
Поставь `<script>` посередине, как везде

2022-09-21 22:49 UTC, danilkach commented on src/App.vue
> +body {
Sass?

2022-09-21 22:50 UTC, danilkach commented on src/App.vue
> +  <nav-component></nav-component>
Можно одинарный тег использовать

2022-09-21 22:51 UTC, danilkach commented
Почему у нас иконки в `.png`? Из фигмы можно экспортировать иконки в векторе. И для чего нужен файл logo.png?

2022-09-21 22:52 UTC, danilkach commented
И, кстати, почему ветка называется `nav-fix`, если фиксить еще нечего было?)

2022-09-21 22:58 UTC, danilkach commented on src/components/NavComponent.vue
> +      <input type="image" class="Enter" :src="require(`@/assets/Enter.png`)" />
К тому же ты мог обратить внимание, что в фигме этот компонент будет иметь три разные вариации в зависимости от *авторизованности* пользователя. К примеру, пользователь, который не авторизовался будет видеть иконку в форме двери, а после авторизации уже будет либо иконка, которую ты добавил, либо закругленная аватарка пользователя

2022-09-21 23:00 UTC, danilkach commented on src/App.vue
> +  <nav-component></nav-component>
Как будем поступать со страницами, где отображать nav-component не нужно?

2022-09-22 04:36 UTC, Juffin-U commented
Могу переместить из app в каждый компонент отдельно 
У нас ещё нет полного макета так что я не знаю где у нас используется навбар 
--
Отправлено из Mail.ru для Android четверг, 22 сентября 2022г., 06:01 +07:00 от Danil Dyachenko  ***@***.*** :

***@***.*** commented on this pull request.
>----------------------------------------------------------------------
>In  src/App.vue :
> @@ -1,9 +1,16 @@
> 
>-  
>-  
>-  
>+  
>
>Как будем поступать со страницами, где отображать nav-component не нужно?
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  @ github . com>

2022-09-22 04:38 UTC, Juffin-U commented
Наша фигма совсем не структурированна и заметить в ней что-то сложно 
Я могу внести эти правки но для этого нужно сначала получить событие авторизации или её отсутствия 
--
Отправлено из Mail.ru для Android четверг, 22 сентября 2022г., 05:58 +07:00 от Danil Dyachenko  ***@***.*** :

***@***.*** commented on this pull request.
>----------------------------------------------------------------------
>In  src/components/NavComponent.vue :
> @@ -0,0 +1,53 @@
>+
>+  
>
>+    
>+    
>
>+      
>
>+        
>
>+          {{ item }}
>+        
>+      
>+      
>
>К тому же ты мог обратить внимание, что в фигме этот компонент будет иметь три разные вариации в зависимости от  авторизованности пользователя. К примеру, пользователь, который не авторизовался будет видеть иконку в форме двери, а после авторизации уже будет либо иконка, которую ты добавил, либо закругленная аватарка пользователя
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  @ github . com>

2022-09-22 04:40 UTC, Juffin-U commented
Лого пнг остался от моего проекта (я его создал ещё до тебя) 
--
Отправлено из Mail.ru для Android четверг, 22 сентября 2022г., 05:51 +07:00 от Danil Dyachenko  ***@***.*** :

>Почему у нас иконки в .png? Из фигмы можно экспортировать иконки в векторе. И для чего нужен файл logo.png?
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  @ github . com>

2022-09-22 04:43 UTC, danilkach commented
> Наша фигма совсем не структурированна и заметить в ней что-то сложно
В фигме достаточно мусора, но, что касается navbar'а, там все нормально. В любому случае, ты можешь у Антона или у нас спросить, если что-то непонятно.

2022-09-22 04:43 UTC, Juffin-U commented
Потому что я видел вёрстку нава только не десктоп в фигме
--
Отправлено из Mail.ru для Android четверг, 22 сентября 2022г., 05:47 +07:00 от Danil Dyachenko  ***@***.*** :

***@***.*** commented on this pull request.
>----------------------------------------------------------------------
>In  src/components/NavComponent.vue :
> @@ -0,0 +1,53 @@
>+
>+  
>
>
>Почему Desktop?
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  @ github . com>

2022-09-22 04:44 UTC, Juffin-U commented
Transitions подойдёт? 
--
Отправлено из Mail.ru для Android четверг, 22 сентября 2022г., 05:44 +07:00 от Danil Dyachenko  ***@***.*** :

***@***.*** commented on this pull request.
>----------------------------------------------------------------------
>In  src/components/NavComponent.vue :
> @@ -0,0 +1,53 @@
>+
>+  
>
>+    
>+    
>
>+      
>
>
>Опять же, naming. Нужно поразмыслить, какие сущности верстаются. Links - это ссылки, например, такие:
>https://natribu.org/
>http://0.0.0.0:5000/
>https://yandex.ru/
>В рамках навигационной панели, как я понял из контекста этого компонента, ты делаешь навигационные кнопки, поэтому называть их ссылками некорректно
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  @ github . com>

2022-09-22 04:45 UTC, danilkach commented
> Потому что я видел вёрстку нава только не десктоп в фигме

В мобилке "нава", как такого, и нет. Если там и будет меню, то это другое

2022-09-22 04:47 UTC, Juffin-U commented
Я не дизайнер на проекте 
Этот впринципе вполне гибкий, но по-хорошему навбар следует отображать вертикально в мобильной версии
--
Отправлено из Mail.ru для Android четверг, 22 сентября 2022г., 05:37 +07:00 от Danil Dyachenko  ***@***.*** :

***@***.*** commented on this pull request.
>----------------------------------------------------------------------
>In  src/components/NavComponent.vue :
> +};
>+
>+
>+

2022-09-22 04:48 UTC, Juffin-U commented
transitionsAndLogInSegment? 
--
Отправлено из Mail.ru для Android четверг, 22 сентября 2022г., 05:36 +07:00 от Danil Dyachenko  ***@***.*** :

***@***.*** commented on this pull request.
>----------------------------------------------------------------------
>In  src/components/NavComponent.vue :
> +  justify-content: $justifyContentPar
***@***.*** font
>+  font-family: Inter, sans-serif
>+  font-style: normal
>+  font-size: 18px
>+  line-height: 19.36px
>+  font-weight: 400
>+.navDesktop
>+  width: 100vw
>+  padding-left: 30px
>+  height: 70px
>+  position: fixed
>+  z-index: 1
>+  background-color: white
>+  @include displayRow
>+.linksAndEnter
>
>Ссылки и входить? Непонятное название стиля
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  @ github . com>

2022-09-22 04:49 UTC, Juffin-U commented
В коментах к репе был пункт про локальную отладку вся страница хом падже для этого и создана
--
Отправлено из Mail.ru для Android четверг, 22 сентября 2022г., 05:35 +07:00 от Danil Dyachenko  ***@***.*** :

***@***.*** commented on this pull request.
>----------------------------------------------------------------------
>In  src/views/HomePage.vue :
> +

2022-09-22 04:50 UTC, Juffin-U commented
Для отладки, не более
--
Отправлено из Mail.ru для Android четверг, 22 сентября 2022г., 05:34 +07:00 от Danil Dyachenko  ***@***.*** :

***@***.*** commented on this pull request.
>----------------------------------------------------------------------
>In  src/views/HomePage.vue :
> @@ -0,0 +1,39 @@
>+
>+  
>
>+    
>
>+      
>
>+    
>+  
>+
>+
>+

2022-09-22 04:54 UTC, danilkach commented
> Могу переместить из app в каждый компонент отдельно У нас ещё нет полного макета так что я не знаю где у нас используется навбар

Дело не в этом. Нужно попробовать придумать способ условно его отображать, не проставляя вручную отдельно на каждой странице компонент

2022-09-22 04:57 UTC, danilkach commented
> Transitions подойдёт?

Подумай еще. Transition - это как переход вещества между агрегатными состояниями. В данному случае, это может быть, например, pageLink, но, опять же, стало бы яснее, когда ты продумал бы структуру нава, который, как мы уже говорили, может внешне отличаться

2022-09-22 04:58 UTC, danilkach commented
> Я не дизайнер на проекте Этот впринципе вполне гибкий, но по-хорошему навбар следует отображать вертикально в мобильной версии

Это на что ответ? Отпиши в соответствующий коммент

2022-09-22 04:59 UTC, danilkach commented
> transitionsAndLogInSegment?

Попробуй еще подумать

2022-09-22 05:00 UTC, danilkach commented
> В коментах к репе был пункт про локальную отладку вся страница хом падже для этого и создана

Ответь в коммент, не показывает, на что ты ответил

2022-09-22 05:02 UTC, danilkach commented
> Для отладки, не более

Локальные, отладочные, тестовые данные не должны попадать в PR, потому что в итоге они окажутся в master'е и соответственно у остальных. Ознакомься с идеями MR/PR в Github

2022-09-22 05:07 UTC, Juffin-U commented on src/components/NavComponent.vue
> +.navDesktop
Я не дизайнер на проекте Этот впринципе вполне гибкий, но по-хорошему навбар следует отображать вертикально в мобильной версии

2022-09-22 05:13 UTC, danilkach commented on src/components/NavComponent.vue
> +.navDesktop
А к чему это? Стили ты пишешь, дизайнер макет верстает. Как это реализовывать - исключительно вопрос твоей фантазии и навыков

2022-09-22 05:15 UTC, danilkach commented on src/components/NavComponent.vue
> +.navDesktop
По поводу нейминга: у нас навбар будет в десктопе, а что будет на мобилке будет видно, когда до этого дойдет дело. И называть <вставьте бургер> меню в мобилке навбар тоже было бы странно

2022-09-22 06:24 UTC, danilkach commented on src/App.vue
> -  </nav>
Одинарный тег?

2022-09-22 06:26 UTC, danilkach commented on src/App.vue
> +  <nav-component></nav-component>
Одинарный тег?

2022-09-22 06:26 UTC, danilkach commented on src/App.vue
> +<style lang="scss">
Sass?

2022-09-22 06:28 UTC, danilkach commented on src/components/NavComponent.vue
> +  <div class="navDesktop">
Все еще Desktop

2022-09-22 06:30 UTC, danilkach commented on src/components/NavComponent.vue
> +    <div class="hyperlinkAndLogInPanel">
Ужас. Предлагаю: navButtonsContainer

2022-09-22 06:30 UTC, danilkach commented on src/components/NavComponent.vue
> +      <div class="hyperlink">
navButton

2022-09-22 06:30 UTC, danilkach commented on src/components/NavComponent.vue
> +      <input type="image" class="Enter" :src="require(`@/assets/LogIn.svg`)" />
class="Enter"?

2022-09-22 06:31 UTC, danilkach commented on src/components/NavComponent.vue
> +          <router-link class="link" :to="item[0]">
А в какой HTML-элемент в итоге <router-link> транслируется?

2022-09-22 06:32 UTC, danilkach commented on src/components/NavComponent.vue
> +      <input type="image" class="Enter" :src="require(`@/assets/LogIn.svg`)" />
Окей, а как менять картинку будет, когда пользователь авторизован?

2022-09-22 06:33 UTC, danilkach commented on src/components/NavComponent.vue
> +      hyperlink: [
hyperlink**s**

Но лучше было бы что-то вроде pathsToPages

2022-09-22 06:37 UTC, danilkach commented on src/components/NavComponent.vue
> +@mixin font
А точно есть смысл использовать примесь? Если шрифт задать на самый верхний контейнер, то его дети не унаследуют его?

2022-09-22 06:37 UTC, danilkach commented on src/components/NavComponent.vue
> +.hyperlinkAndLogInPanel
Выше упоминул про нейминг

2022-09-22 06:37 UTC, danilkach commented on src/components/NavComponent.vue
> +.navDesktop
Naming

2022-09-22 06:45 UTC, danilkach requested changes
Плюс все так же валяется лишняя png'шка

2022-09-22 06:45 UTC, danilkach commented on src/components/NavComponent.vue
> +.hyperlink
Naming

2022-09-22 06:45 UTC, danilkach commented on src/router/index.js
> +        import(/* webpackChunkName: "about" */ "../views/СoursesPage.vue"),
Зачем комменты?

2022-09-22 06:45 UTC, danilkach commented on src/App.vue
> +  <nav-component></nav-component>
Одинарный тег?

2022-09-22 06:45 UTC, danilkach commented on src/App.vue
> +<style lang="scss">
Sass?

2022-09-22 06:45 UTC, danilkach commented on src/components/NavComponent.vue
> +  <div class="navDesktop">
Все еще Desktop

2022-09-22 06:45 UTC, danilkach commented on src/components/NavComponent.vue
> +    <div class="hyperlinkAndLogInPanel">
Ужас. Предлагаю: navButtonsContainer

2022-09-22 06:45 UTC, danilkach commented on src/components/NavComponent.vue
> +      <div class="hyperlink">
navButton

2022-09-22 06:45 UTC, danilkach commented on src/components/NavComponent.vue
> +          <router-link class="link" :to="item[0]">
А в какой HTML-элемент <router-link> в итоге транслируется?

2022-09-22 06:45 UTC, danilkach commented on src/components/NavComponent.vue
> +      <input type="image" class="Enter" :src="require(`@/assets/LogIn.svg`)" />
class="Enter"?

2022-09-22 06:45 UTC, danilkach commented on src/components/NavComponent.vue
> +      <input type="image" class="Enter" :src="require(`@/assets/LogIn.svg`)" />
Окей, а как менять картинку будет, когда пользователь авторизован?

2022-09-22 06:45 UTC, danilkach commented on src/components/NavComponent.vue
> +      hyperlink: [
hyperlink**s**

Но лучше было бы что-то вроде pathsToPages

2022-09-22 06:45 UTC, danilkach commented on src/components/NavComponent.vue
> +@mixin font
А точно есть смысл использовать примесь? Если шрифт задать на самый верхний контейнер, то его дети не унаследуют его?

2022-09-22 06:45 UTC, danilkach commented on src/components/NavComponent.vue
> +.navDesktop
Naming

2022-09-22 06:45 UTC, danilkach commented on src/components/NavComponent.vue
> +.hyperlinkAndLogInPanel
Выше упомянул про naming

2022-09-22 06:45 UTC, danilkach commented on src/views/HomePage.vue
> +  name: "HomePage",
Запятая лишняя

2022-09-22 06:45 UTC, danilkach commented on src/views/MaterialsPage.vue
> +<style scoped>
Sass?

2022-09-22 06:45 UTC, danilkach commented on src/views/ServicesPage.vue
> +<style scoped>
Sass?

2022-09-22 06:45 UTC, danilkach commented on src/views/СoursesPage.vue
> +<style scoped>
Sass?

2022-09-22 12:12 UTC, danilkach commented on src/components/NavComponent.vue
> +.hyperlink
Test

2022-10-11 08:55 UTC, Juffin-U commented
Ок
--
Отправлено из Mail.ru для Android четверг, 22 сентября 2022г., 05:46 +07:00 от Danil Dyachenko  ***@***.*** :

***@***.*** commented on this pull request.
>----------------------------------------------------------------------
>In  src/components/NavComponent.vue :
> @@ -0,0 +1,53 @@
>+
>+  
>
>+    
>+    
>
>+      
>
>+        
>
>+          {{ item }}
>
>Не размещай текст в div'ах. Используй 
>или более уместный здесь 
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  @ github . com>

2022-10-11 09:13 UTC, Juffin-U commented
Можно
Если это принципиально важно буду использовать одинарный 
--
Отправлено из Mail.ru для Android четверг, 22 сентября 2022г., 05:50 +07:00 от Danil Dyachenko  ***@***.*** :

***@***.*** commented on this pull request.
>----------------------------------------------------------------------
>In  src/App.vue :
> @@ -1,9 +1,16 @@
> 
>-  
>-  
>-  
>+  
>
>Можно одинарный тег использовать
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  @ github . com>

2022-10-11 09:14 UTC, Juffin-U commented
Это тестовая страница там по хорошему рабочих стилей вообще нет
--
Отправлено из Mail.ru для Android четверг, 22 сентября 2022г., 05:49 +07:00 от Danil Dyachenko  ***@***.*** :

***@***.*** commented on this pull request.
>----------------------------------------------------------------------
>In  src/App.vue :
>  
> 
>

2022-10-12 18:02 UTC, danilkach commented
@Juffin-U просили же не отвечать через почту, непонятно, на что ты ответил. Сделай новый PR, в этом уже хрен разберешь что, где и куда

2023-03-19 19:23 UTC, closed without merging